# Relaxed.Ruby.Style

AllCops:
  Exclude:
    - 'vendor/**/*'
    - '**/vendor/**/*'
    - 'spec/dummy/**/*'
    - 'sandbox/**/*'
    - '**/templates/**/*'
    - 'lib/**/*'
    - '*.gemspec'
    - 'spec/spec_helper.rb'
  TargetRubyVersion: 2.4

# We use class vars and will have to continue doing so for compatability
Style/ClassVars:
  Enabled: false

# We need these names for backwards compatability
Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

# This has been used for customization
Style/MutableConstant:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

# We can use good judgement here
Style/RegexpLiteral:
  Enabled: false

# Unicode comments are useful
Style/AsciiComments:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# Symbol Arrays are ok and the %i syntax widely unknown
Style/SymbolArray:
  Enabled: false

# We use a lot of
#
#     expect {
#       something
#     }.to { happen }
#
# syntax in the specs files.
Lint/AmbiguousBlockAssociation:
  Exclude:
    - '*/spec/**/*'
    - 'spec/**/*' # For the benefit of apps that inherit from this config

# We use eval to add common_spree_dependencies into the Gemfiles of each of our gems
Security/Eval:
  Exclude:
    - 'Gemfile'
    - 'common_spree_dependencies.rb'
    - '*/Gemfile'

Naming/VariableNumber:
  Enabled: false

# Write empty methods as you wish.
Style/EmptyMethod:
  Enabled: false

# From http://relaxed.ruby.style/

Style/Alias:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylealias

Style/BeginBlock:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylebeginblock

Style/BlockDelimiters:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleblockdelimiters

Style/Documentation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledocumentation

Layout/DotPosition:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledotposition

Style/DoubleNegation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledoublenegation

Style/EndBlock:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleendblock

Style/FormatString:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleformatstring

Style/IfUnlessModifier:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleifunlessmodifier

Style/Lambda:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylelambda

Style/ModuleFunction:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylemodulefunction

Style/MultilineBlockChain:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylemultilineblockchain

Style/NegatedIf:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylenegatedif

Style/NegatedWhile:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylenegatedwhile

Style/ParallelAssignment:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleparallelassignment

Style/PercentLiteralDelimiters:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylepercentliteraldelimiters

Style/PerlBackrefs:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleperlbackrefs

Style/Semicolon:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesemicolon

Style/SignalException:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesignalexception

Style/SingleLineBlockParams:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesinglelineblockparams

Style/SingleLineMethods:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesinglelinemethods

Layout/SpaceBeforeBlockBraces:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylespacebeforeblockbraces

Layout/SpaceInsideParens:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylespaceinsideparens

Style/SpecialGlobalVars:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylespecialglobalvars

Style/StringLiterals:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylestringliterals

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylewhileuntilmodifier

Lint/AmbiguousRegexpLiteral:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#lintambiguousregexpliteral

Lint/AssignmentInCondition:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#lintassignmentincondition

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# json.() is idiomatic in jbuilder files
Style/LambdaCall:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - id
    - to
    - _

# Rubocop doesn't understand side-effects
Style/IdenticalConditionalBranches:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true

Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: true

Gemspec/RequireMFA: # new in 1.23
  Enabled: true

Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true

Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true

Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true

Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true

Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true

Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true

Lint/DeprecatedConstants: # new in 1.8
  Enabled: true

Lint/DuplicateBranch: # new in 1.3
  Enabled: true

Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true

Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true

Lint/EmptyBlock: # new in 1.1
  Enabled: true

Lint/EmptyClass: # new in 1.3
  Enabled: true

Lint/EmptyInPattern: # new in 1.16
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true

Lint/ItWithoutArgumentsInBlock: # new in 1.59
  Enabled: true

Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true

Lint/LiteralAssignmentInCondition: # new in 1.58
  Enabled: true

Lint/MixedCaseRange: # new in 1.53
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true

Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true

Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true

Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true

Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true

Lint/RedundantRegexpQuantifiers: # new in 1.53
  Enabled: true

Lint/RefinementImportMethods: # new in 1.27
  Enabled: true

Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true

Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true

Lint/SymbolConversion: # new in 1.9
  Enabled: true

Lint/ToEnumArguments: # new in 1.1
  Enabled: true

Lint/TripleQuotes: # new in 1.9
  Enabled: true

Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true

Lint/UselessRescue: # new in 1.43
  Enabled: true

Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true

Metrics/CollectionLiteralLength: # new in 1.47
  Enabled: true

Naming/BlockForwarding: # new in 1.24
  Enabled: true

Security/CompoundHash: # new in 1.28
  Enabled: true

Security/IoMethods: # new in 1.22
  Enabled: true

Style/ArgumentsForwarding: # new in 1.1
  Enabled: true

Style/ArrayIntersect: # new in 1.40
  Enabled: true

Style/CollectionCompact: # new in 1.2
  Enabled: true

Style/ComparableClamp: # new in 1.44
  Enabled: true

Style/ConcatArrayLiterals: # new in 1.41
  Enabled: true

Style/DataInheritance: # new in 1.49
  Enabled: true

Style/DirEmpty: # new in 1.48
  Enabled: true

Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true

Style/EmptyHeredoc: # new in 1.32
  Enabled: true

Style/EndlessMethod: # new in 1.8
  Enabled: true

Style/EnvHome: # new in 1.29
  Enabled: true

Style/ExactRegexpMatch: # new in 1.51
  Enabled: true

Style/FetchEnvVar: # new in 1.28
  Enabled: true

Style/FileEmpty: # new in 1.48
  Enabled: true

Style/FileRead: # new in 1.24
  Enabled: true

Style/FileWrite: # new in 1.24
  Enabled: true

Style/HashConversion: # new in 1.10
  Enabled: true

Style/HashExcept: # new in 1.7
  Enabled: true

Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: true

Style/InPatternThen: # new in 1.16
  Enabled: true

Style/MagicCommentFormat: # new in 1.35
  Enabled: true

Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true

Style/MapToHash: # new in 1.24
  Enabled: true

Style/MapToSet: # new in 1.42
  Enabled: true

Style/MinMaxComparison: # new in 1.42
  Enabled: true

Style/MultilineInPatternThen: # new in 1.16
  Enabled: true

Style/NegatedIfElseCondition: # new in 1.2
  Enabled: true

Style/NestedFileDirname: # new in 1.26
  Enabled: true

Style/NilLambda: # new in 1.3
  Enabled: true

Style/NumberedParameters: # new in 1.22
  Enabled: true

Style/NumberedParametersLimit: # new in 1.22
  Enabled: true

Style/ObjectThen: # new in 1.28
  Enabled: true

Style/OpenStructUse: # new in 1.23
  Enabled: true

Style/OperatorMethodCall: # new in 1.37
  Enabled: true

Style/QuotedSymbols: # new in 1.16
  Enabled: true

Style/RedundantArgument: # new in 1.4
  Enabled: true

Style/RedundantArrayConstructor: # new in 1.52
  Enabled: true

Style/RedundantConstantBase: # new in 1.40
  Enabled: true

Style/RedundantCurrentDirectoryInPath: # new in 1.53
  Enabled: true

Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: true

Style/RedundantEach: # new in 1.38
  Enabled: true

Style/RedundantFilterChain: # new in 1.52
  Enabled: true

Style/RedundantHeredocDelimiterQuotes: # new in 1.45
  Enabled: true

Style/RedundantInitialize: # new in 1.27
  Enabled: true

Style/RedundantLineContinuation: # new in 1.49
  Enabled: true

Style/RedundantRegexpArgument: # new in 1.53
  Enabled: true

Style/RedundantRegexpConstructor: # new in 1.52
  Enabled: true

Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true

Style/RedundantStringEscape: # new in 1.37
  Enabled: true

Style/ReturnNilInPredicateMethodDefinition: # new in 1.53
  Enabled: true

Style/SelectByRegexp: # new in 1.22
  Enabled: true

Style/SingleLineDoEndBlock: # new in 1.57
  Enabled: true

Style/StringChars: # new in 1.12
  Enabled: true

Style/SuperWithArgsParentheses: # new in 1.58
  Enabled: true

Style/SwapValues: # new in 1.1
  Enabled: true

Style/YAMLFileRead: # new in 1.53
  Enabled: true
